services:
  web:
    container_name: apache-php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT_WEB}:${EXP}"
    volumes:
      - ./src:/var/www/html
      - ./:/app
    user: "${UID}:${GID}" 
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: >
      bash -c "
        npm --cache /tmp/.npm run dev &
        apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${MYADMIN_PORT}:${EXP}"
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
